### PR TITLE
Update TwitterAPI.py

### PR DESCRIPTION
**Pull request by cloudshapes**
Update request to allow timeout to be specified as a function parameter

Been getting some TwitterAPI timeouts when submitting a request, so wondered if it would be possible to change request as follows:

def request(self, resource, params=None, files=None, timeout=None):

i.e. add a timeout parameter.

### CODE REVIEW

**Comment by geduldig** [comment]
Thank you for the patch. I probably will not use it only because I am working on a fix right now. I hope to complete testing within a couple of weeks. If you want to get a preview of the fix check out the [fault_tolerant_stream](https://github.com/geduldig/TwitterAPI/tree/fault_tolerant_stream). Feedback is appreciated! 

I'll leave this open until I merge the fix.

**Comment by cloudshapes** [comment]
Hi Jonas,

Thanks for the reply. I can see you've made it more fault tolerant, but the
issue I'm having is that I'm getting the odd timeout from the requests
call. If I manually set the timeout value to say 50 seconds, I don't.
Whilst your fault tolerant patch will improve reporting, will it give me
the control I would find handy over the timeout?

Thanks,
R





On 26 January 2015 at 15:39, Jonas Geduldig <notifications@github.com>
wrote:

> Thank you for the patch. I probably will not use it only because I am
> working on a fix right now. I hope to complete testing within a couple of
> weeks. If you want to get a preview of the fix check out the
> fault_tolerant_stream
> <https://github.com/geduldig/TwitterAPI/tree/fault_tolerant_stream>.
> Feedback is appreciated!
>
> I'll leave this open until I merge the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geduldig/TwitterAPI/pull/44#issuecomment-71479891>.
>



-- 

Kind regards,
Roland

Roland Dunn
--------------------------

m: +44 (0)7967 646 789
e: roland.dunn@gmail.com
w: http://www.cloudshapes.co.uk/
https://twitter.com/roland_dunn
http://uk.linkedin.com/in/rolanddunn

**Comment by geduldig** [comment]
What is the request you are making? How frequently does it time out? What is the time out error you are receiving?

**Comment by cloudshapes** [comment]
- Request:

    api = TwitterAPI(**settings.TWITTER_OAUTH)
    r = api.request(
        'statuses/user_timeline',
        {'screen_name': handle, 'count': 50}
    )


- How frequently: Say 10% of the time.

- Error:

  File "python-env/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py",
line 107, in request
    proxies=self.proxies)
  File "python-env/lib/python2.7/site-packages/requests/sessions.py", line
456, in request
    resp = self.send(prep, **send_kwargs)
  File "python-env/lib/python2.7/site-packages/requests/sessions.py", line
559, in send
    r = adapter.send(request, **kwargs)
  File "python-env/lib/python2.7/site-packages/requests/adapters.py", line
384, in send
    raise Timeout(e, request=request)


R



On 26 January 2015 at 15:56, Jonas Geduldig <notifications@github.com>
wrote:

> What is the request you are making? How frequently does it time out? What
> is the time out error you are receiving?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geduldig/TwitterAPI/pull/44#issuecomment-71482970>.
>



-- 

Kind regards,
Roland

Roland Dunn
--------------------------

m: +44 (0)7967 646 789
e: roland.dunn@gmail.com
w: http://www.cloudshapes.co.uk/
https://twitter.com/roland_dunn
http://uk.linkedin.com/in/rolanddunn

**Comment by geduldig** [comment]
Seems odd that you don't get a response from Twitter within 5 seconds. 50 seconds is a very long time. My first thought is that there is some sort of network-related issue going on. For this reason I am hesitant to add a timeout parameter. Do you have any thoughts what is causing the timeout? If the timeout is unique to your situation my preference would be for you to increase `REST_TIMEOUT` in [constants.py](https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py).

**Comment by cloudshapes** [comment]
Nope, no idea I'm afraid. It's on a decent server, decent network conn,
etc, so should be fine.

I'm reluctant to change variable in constants.py as it'll just be
overwritten by any future lib, also bit clumsy for setting up on other
dev's servers. We automate as much of env as possible, this is kind of
tricky to automate!








On 26 January 2015 at 16:22, Jonas Geduldig <notifications@github.com>
wrote:

> Seems odd that you don't get a response from Twitter within 5 seconds. 50
> seconds is a very long time. My first thought is that there is some sort of
> network-related issue going on. For this reason I am hesitant to add a
> timeout parameter. Do you have any thoughts what is causing the timeout? If
> the timeout is unique to your situation my preference would be for you to
> increase REST_TIMEOUT in constants.py
> <https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geduldig/TwitterAPI/pull/44#issuecomment-71487804>.
>



-- 

Kind regards,
Roland

Roland Dunn
--------------------------

m: +44 (0)7967 646 789
e: roland.dunn@gmail.com
w: http://www.cloudshapes.co.uk/
https://twitter.com/roland_dunn
http://uk.linkedin.com/in/rolanddunn

**Comment by geduldig** [comment]
Rather than increasing the timeout to 50 seconds and possibly waiting that amount of time for a connection, why not leave the timeout at 5 seconds and catch `requests.exceptions.Timeout`, then re-try your request immediately?

**Comment by cloudshapes** [comment]
Yeah, could look at that. Will try when I get a moment.
R


On 26 January 2015 at 16:39, Jonas Geduldig <notifications@github.com>
wrote:

> Rather than increasing the timeout to 50 seconds and possibly waiting that
> amount of time for a connection, why not leave the timeout at 5 seconds and
> catch requests.exceptions.Timeout, then re-try your request immediately?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geduldig/TwitterAPI/pull/44#issuecomment-71491062>.
>



-- 

Kind regards,
Roland

Roland Dunn
--------------------------

m: +44 (0)7967 646 789
e: roland.dunn@gmail.com
w: http://www.cloudshapes.co.uk/
https://twitter.com/roland_dunn
http://uk.linkedin.com/in/rolanddunn

**Comment by cloudshapes** [comment]
Yep, that seems to OK.
Thanks,

R



On 26 January 2015 at 18:15, Roland Dunn <roland.dunn@gmail.com> wrote:

> Yeah, could look at that. Will try when I get a moment.
> R
>
>
> On 26 January 2015 at 16:39, Jonas Geduldig <notifications@github.com>
> wrote:
>
>> Rather than increasing the timeout to 50 seconds and possibly waiting
>> that amount of time for a connection, why not leave the timeout at 5
>> seconds and catch requests.exceptions.Timeout, then re-try your request
>> immediately?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geduldig/TwitterAPI/pull/44#issuecomment-71491062>.
>>
>
>
>
> --
>
> Kind regards,
> Roland
>
> Roland Dunn
> --------------------------
>
> m: +44 (0)7967 646 789
> e: roland.dunn@gmail.com
> w: http://www.cloudshapes.co.uk/
> https://twitter.com/roland_dunn
> http://uk.linkedin.com/in/rolanddunn
>



-- 

Kind regards,
Roland

Roland Dunn
--------------------------

m: +44 (0)7967 646 789
e: roland.dunn@gmail.com
w: http://www.cloudshapes.co.uk/
https://twitter.com/roland_dunn
http://uk.linkedin.com/in/rolanddunn

**Pull request closed without merging**
