### PR TITLE
Add timeout to api.request

### LINKED ISSUE #84: Request timeout is not adjustable
We are using TwitterAPI and its REST-interface for our project. Lately we ran several times into issues regarding timeouts. Hence, a maximum timeout of five seconds does not seem sufficient.

### PR DESCRIPTION
**Pull request by Bensk1**
This fixes #84 by increasing the `CONNECTION_TIMEOUT` constant from `5` to `10`. Furthermore it adds a `timeout_override` parameter to the `request` method.

### CODE REVIEW

**Comment by geduldig** [comment]
Hi - 

I have a couple of questions regarding the proposed changes. Are there special conditions that make it necessary to override CONNECTION_TIMEOUT, STREAMING_TIMEOUT, and REST_TIMEOUT? 

I have not come across a case where it was necessary to override any of the timeouts, though I can image the possibility of the need.

My second question is, instead of your proposed changes, why not simply set new values, as required, for any of the global default timeouts? For instance, why not put `constants.CONNECTION_TIMEOUT = 10` in your code?

Jonas

**Comment by piepmatz** [comment]
Hi Jonas,

I'm working with @Bensk1 on the same project.

We experienced quite often within the recent weeks that 5 seconds were simply not enough. The request timed out. Using 10 seconds as default value worked for us.

Setting `constants.CONNECTION_TIMEOUT = 10` has no effect: During the prior `from TwitterAPI import constants` TwitterAPI's `__init__.py` is loaded which loads the TwitterAPI module which loads all constants.
So when setting a custom timeout value it is already too late as the TwitterAPI module will use the default values loaded earlier.

**Comment by geduldig** [comment]
Hi-

Of course you are correct. 

I think it unusual that it is taking longer than 5 seconds to connect. Still, if that is the case, we might as well add the ability to override. My experience is typically under a second to connect, and I would not want to wait 10 seconds to get a connection timeout. So, rather than changing CONNECTION_TIMEOUT to 10, would you be adverse to having overrides for both the connection and the read timeouts, and leaving CONNECTION_TIMEOUT unchanged?

Jonas

**Comment by Bensk1** [comment]
For sure, it's unusual that it takes more than five seconds to connect and I would not expect that. For the REST read timeout, I would not be so sure. When looking for really old tweets, they might be stored at the bottom of the memory/storage hierarchy and this might take a long time to process. We will investigate what causes the timeout.

**Comment by geduldig** [comment]
That you are looking for old tweets would not cause a timeout per se. Such a request would use a tweet id or tweet date to jump to an older position, so you should expect the same elapsed time to connect and to read during the request as you would for a request of recent tweets.

The fact that these (connection?) timeouts are infrequent makes me think that in your use case you are attempting to keep your program running over a long period of time during which you are connecting and requesting data. Is that accurate?

**Comment by Bensk1** [comment]
I am not sure about that. We are not specifically asking the API for a single old tweet. We are asking for the oldest tweets of certain accounts. Furthermore, we are still not sure if we experience connection or read timeouts. And we are not keeping our program running for a long period of time, it is more less sporadically connection to the Twitter API.

**Comment by geduldig** [comment]
How are you requesting oldest tweets of an account? I would assume you are doing some sort of paging.

When `request` times out it throws a `TwitterConnectionError` which contains the original error class which will determine what caused the timeout. If you turn on logging you will see these details printed out. This [example](https://github.com/geduldig/TwitterAPI/blob/master/examples/sample_freq.py) shows how to turn on logging.

**Comment by Bensk1** [comment]
We are using [user statuses/user_timeline](https://dev.twitter.com/rest/reference/get/statuses/user_timeline). However, we will study the logs.

**Comment by geduldig** [comment]
With `statuses/user_timeline` you would use the `max_id` parameter to get older tweets. This request takes no longer to fulfill than requesting the most recent tweets. All you are changing is which tweet id to start looking from.

**Comment by Bensk1** [comment]
From an API perspective this sounds correct. However, for the internal retrieval at twitter, I would expect twitter to store the most recent tweets at a higher level of the memory hierarchy where you can retrieve them really quick. Old tweets which are only retrieved really rarely could be stored in a way (slow HDDs) that it might take longer on twitter's end to retrieve them and send them back. This would make sense because storage would be much cheaper for these tweets. But I don't know anything detailed about their storage, these are just assumptions.

**Comment by geduldig** [comment]
Okay. It sounds like you need to do some more investigating. I've been doing this a while. I write code that stays running for long periods of time. If there are timeouts they are rare anomalies, and the code simply retries the request. Rate limiting is usually the harder issue to deal with. Let me know what you find.

**Comment by geduldig** [comment]
Did you figure out the cause of your timeouts?

**Comment by n1rocket** [comment]
Hi! I need change timeout because when i try to upload media from task un celery, this return timeout always.

**Comment by geduldig** [comment]
Please post a short example that demonstrates the timeout you are referring to.

**Comment by n1rocket** [comment]
`[2017-05-21 13:27:31,407: ERROR/PoolWorker-1] Task firstapp.tasks.post_twitter[d46af40b-3c6f-496c-8fe1-3a1b1007798f] raised unexpected: TwitterConnectionErr
or(ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='upload.twitter.com', port=443): Read timed out. (read timeout=5)",),),)`

**Comment by geduldig** [comment]
I meant, can you create a short code example that exhibits the timeout issue, and then post the code so I can look at exactly what is going on?

**Comment by geduldig** [comment]
I'm closing this until someone can provide an example that demonstrates a particular timeout. This timeout is not something I have experienced, and it be caused by some unique condition.

**Comment by Bensk1** [comment]
I did some experiments with our setup (consecutive API calls) and the exact same API paths. To be sure to not exceed the rate limit, I also monitored the rate limit. The interesting thing was that I even got the timeouts for the rate limit calls.

Please find attached a small example, which should demonstrate the problem. I ran the example script several times. On average eleven out of 50 calls time out.


```
from TwitterAPI import TwitterAPI

TWITTER_CONSUMER_KEY = "YOUR_APPLICATION_KEY"
TWITTER_CONSUMER_SECRET = "YOUR_APPLICATION_SECRET"

twitter = TwitterAPI(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, auth_type='oAuth2')

error_count = 0
for i in range(50):
    try:
        print(twitter.request('application/rate_limit_status').json()['resources']['application']['/application/rate_limit_status'])
    except:
        error_count += 1

print("Errors occured %d" % (error_count))
```

**Comment by geduldig** [comment]
I will look at the snippet. Thanks.
Can you clarify how you determine when a timeout has occurred? I don't see that in your code. Or, are you assuming all raised exceptions are timeouts?

**Comment by Bensk1** [comment]
When you run the snippet on the command line, you can see which exception is raised. It is always the same exception, a timeout:

`WARNING:root:<class 'requests.exceptions.ConnectTimeout'> HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/application/rate_limit_status.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106861630>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))`

**Comment by geduldig** [comment]
I ran your code and I get no errors. 

I don't recognize the `VerifiedHTTPSConnection` exception, but it may have something to do with being behind a proxy.

**Comment by Bensk1** [comment]
I am actually not behind a proxy. But you are completely right, I tried my script today with another internet connection and it perfectly worked without any errors. I did not consider my broadband connection to be the problem because my colleague @piepmatz had exactly the same problem at a completely different place. Maybe my ISP is throttling/slowing down repeated accesses to the same url? I will let you know in case I get interesting news on that.

Thanks for your help

**Comment by geduldig** [comment]
I wonder if putting a small wait in between requests would help. I provide a helper class -- `TwitterRestPager` -- to do this which you can check out.

[Doc](http://geduldig.github.io/TwitterAPI/twitterrestpager.html)
[Paging](http://geduldig.github.io/TwitterAPI/paging.html)
[Fault tolerance](http://geduldig.github.io/TwitterAPI/faulttolerance.html)

**Pull request closed without merging**
