### PR TITLE
Handle v2 expansion data

### LINKED ISSUE #156: Handle v2 expansion data in TwitterPager
I'd like to expand the TwitterPager to paginate queries and append results with v2 field expansions.

Here are example query components:
```
ENDPOINT = 'tweets/search/recent'
EXPANSIONS = 'attachments.media_keys'
MEDIA_FIELDS = ['duration_ms',
                'height',
                'media_key',
                'preview_image_url',
                'type',
                'url',
                'width',
                'public_metrics',
                'non_public_metrics',
                'organic_metrics']
```

Queries that use expansions have results with a nested structure.
These results have an 'includes' key that currently gets clobbered by `TwitterPager`
I'd like to just paginate and append to a giant list.

The quick and dirty way I see of modifying `class _RestIterable(object)` `__init__` [here](https://github.com/geduldig/TwitterAPI/blob/4d5c636aea15940907d021b1f6b7a8dc382ae2ad/TwitterAPI/TwitterAPI.py#L295):
```
        if 'errors' in resp:
            self.results = resp['errors']
        # add this >>>>
        elif 'includes' in resp:
            self.results = [resp]
        # <<<<<<
        elif 'statuses' in resp:
            self.results = resp['statuses'] 
```

... but I'm sure there's something more elegant.

Example structure of one page of results:
```
 {'data': [{'attachments': {'media_keys': ['12345']},
            'id': '12345',
            'text': 'some text'},
           {'attachments': {'media_keys': ['12345']},
            'id': '12345',
            'text': "some text'}],
  'includes': {'media': [{'duration_ms': 12345,
                          'height': 12345,
                          'media_key': '12345',
                          'non_public_metrics': {'playback_0_count': 12345,
                                                 'playback_100_count': 12345,
                                                 'playback_25_count': 12345,
                                                 'playback_50_count': 12345,
                                                 'playback_75_count': 12345},
                          'organic_metrics': {'playback_0_count': 12345,
                                              'playback_100_count': 12345,
                                              'playback_25_count': 12345,
                                              'playback_50_count': 12345,
                                              'playback_75_count': 12345,
                                              'view_count': 12345},
                          'preview_image_url': 'some url',
                          'public_metrics': {'view_count': 12345},
                          'type': 'video',
                          'width': 1080},
                          {'duration_ms': 12345,
                          'height': 12345,
                          'media_key': '12345',
                          'non_public_metrics': {'playback_0_count': 12345,
                                                 'playback_100_count': 12345,
                                                 'playback_25_count': 12345,
                                                 'playback_50_count': 12345,
                                                 'playback_75_count': 12345},
                          'organic_metrics': {'playback_0_count': 12345,
                                              'playback_100_count': 12345,
                                              'playback_25_count': 12345,
                                              'playback_50_count': 12345,
                                              'playback_75_count': 12345,
                                              'view_count': 12345},
                          'preview_image_url': 'some url',
                          'public_metrics': {'view_count': 12345},
                          'type': 'video',
                          'width': 1080},
                         ]},
  'meta': {'newest_id': '12345',
                'next_token': 'abc12345',
                'oldest_id': '12345',
               'result_count': 12345}}
```

### PR DESCRIPTION
**Pull request by dylancaponi**
Fixes #156.

Append data as a list element when there's an `includes` key in the results.

If `includes` ever appears in v1 result data this may need to be modified.

### CODE REVIEW

**Comment by andypiper** [comment]
FWIW, there are no plans to make any changes to v1.1 data or to "backport" details like this - it is a totally different platform.

**Comment by dylancaponi** [comment]
@andypiper Are you saying `includes` will never appear in v1 data?
The goal of this change is to pull data from v2 and parse it later.
Existing code parses data and loses anything under the 'includes' key.

**Comment by andypiper** [comment]
Yes, I’d say with a high degree of confidence that the includes JSON values will not come to appear in v1.1 API responses. The whole of the new v2 data format and structure is completely separate and different from the older APIs. It is *not* completely impossible if something incredibly surprising was to happen, but I don’t see how it could be made to work - the stuff you see in includes, is mostly already part of the default v1.1 data structure (e.g. user objects, media etc), so it wouldn’t make a lot of sense.

**Comment by geduldig** [comment]
See my comment in https://github.com/geduldig/TwitterAPI/issues/156.

**Review by JABERMQM — COMMENTED** [review]
- [ ]

**Pull request closed without merging**
