### PR TITLE
WIP - Twitter v2

### PR DESCRIPTION
**Pull request by dylancaponi**
Related to #146 

Adds:

- v2 endpoints

- `version` param in `request` and check in `_prepare_url`

- v2 user lookup example

Todo:

- [ ] Rename `VERSION` or `version` to avoid constant and variable with the same name.

- [ ] test other endpoints OR comment them and add in future PR

### CODE REVIEW

**Comment by geduldig** [comment]
Thank you! I'm making some small adjustments to your code. Also, noticed some peripheral issues that I need to address.

**Comment by dylancaponi** [comment]
@geduldig ok, happy to make those changes on this branch if it's easy to describe them.

**Comment by geduldig** [comment]
I'm keeping your branch and making changes to it.

**Comment by geduldig** [comment]
Version 2.6 now has support for Twitter API Version 2 early release. See the new code examples in the TwitterAPI/examples folder. By default, only Version 1.1 API endpoints will work.

**Comment by geduldig** [comment]
more v2 examples uploaded

**Pull request merged**
